# Generated by Django 2.1.2 on 2018-10-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='book_author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
